Update download-cpi-package.yml

diff --git a/.github/workflows/download-cpi-package.yml b/.github/workflows/download-cpi-package.yml
--- a/.github/workflows/download-cpi-package.yml
+++ b/.github/workflows/download-cpi-package.yml
@@ -36,6 +36,10 @@ jobs:
             https://bd9d77d2trial.authentication.ap21.hana.ondemand.com/oauth/token)
           echo "Token response: $RESPONSE"
           TOKEN=$(echo $RESPONSE | jq -r '.access_token')
+          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
+            echo "Failed to fetch token"
+            exit 1
+          fi
           echo "token=$TOKEN" >> $GITHUB_OUTPUT
 
       - name: Download Interfaces
